require("dotenv").config();

const port=process.env.PORT || 3000;
const MONGODB_CONNECTION_STRING=process.env.MONGODB_CONNECTION_STRING;
const ACCESS_TOKEN_SECRET=process.env.ACCESS_TOKEN_SECRET;
const REFRESH_TOKEN_SECRET=process.env.REFRESH_TOKEN_SECRET;
console.log("MONGODB_CONNECTION_STRING",MONGODB_CONNECTION_STRING)
module.exports={
    port,  
    MONGODB_CONNECTION_STRING,
    ACCESS_TOKEN_SECRET,
    REFRESH_TOKEN_SECRET
};